version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: "playvoice"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./mongodb-keyfile:/opt/keyfile:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: "playvoice"
      MONGO_INITDB_ROOT_PASSWORD: "playvoice"
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/opt/keyfile/mongodb-keyfile"]
    user: "999:999"

volumes:
  mongodata:
    driver: local